
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: available_infosec_development

test:
  <<: *default
  database: available_infosec_test

production:
  url: <%= ENV['DATABASE_URL'] %>